project_id = "jhzmgexprjnpgadkxjup"

[functions.track-rank-rent-conversion]
verify_jwt = false

[functions.import-sitemap]
verify_jwt = true

[functions.generate-client-report]
verify_jwt = false

[functions.check-plugin-status]
verify_jwt = false

[functions.update-user-email]
verify_jwt = true

[functions.fetch-page-titles]
verify_jwt = true

[functions.generate-excel-report]
verify_jwt = true

[functions.generate-pdf-report]
verify_jwt = true

[functions.generate-html-report]
verify_jwt = true

[functions.generate-portal-analytics]
verify_jwt = false